### ISSUE TITLE
세일러문 막는 기능 빼주세요

### ISSUE THREAD

**Issue by heartleth** [dacoonkr/Xenobot#1]
![ㅅㅇㄹㅁ](https://media.tenor.com/images/51783c683298269fd38ee3c2353855d5/tenor.gif)
![ㅅㅇㄹㅁ](https://media.tenor.com/images/5af49c3c0f0a420f675ec040f3dbed5c/tenor.gif)

**Comment by dacoonkr** [comment]
커밋은 안했지만 예전에 뺐습니다

**Comment by heartleth** [comment]
갓
